name: Test - Server Operations

on:
    workflow_dispatch:
        inputs:
            test_type:
                description: "Type of test to run"
                required: true
                default: "file_creation"
                type: choice
                options:
                    - file_creation
                    - health_check
                    - log_check
                    - cleanup
            file_name:
                description: "Name of test file to create (for file_creation test)"
                required: false
                default: "test-deployment.txt"
            message:
                description: "Message to write in test file"
                required: false
                default: "Test deployment successful"

jobs:
    test-operations:
        name: Test Server Operations
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add server to known hosts
              run: |
                  ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

            - name: File Creation Test
              if: ${{ github.event.inputs.test_type == 'file_creation' }}
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
                    cd ${{ secrets.DEPLOY_PATH }}
                    echo '${{ github.event.inputs.message }}' > ${{ github.event.inputs.file_name }}
                    echo 'Timestamp: $(date)' >> ${{ github.event.inputs.file_name }}
                    echo 'GitHub SHA: ${{ github.sha }}' >> ${{ github.event.inputs.file_name }}
                    echo 'Created by: GitHub Actions' >> ${{ github.event.inputs.file_name }}
                    
                    echo 'Test file created successfully:'
                    cat ${{ github.event.inputs.file_name }}
                  "

            - name: Health Check Test
              if: ${{ github.event.inputs.test_type == 'health_check' }}
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
                    cd ${{ secrets.DEPLOY_PATH }}
                    
                    echo '=== Docker Compose Status ==='
                    docker-compose ps
                    
                    echo '=== Container Health ==='
                    docker stats --no-stream
                    
                    echo '=== Disk Usage ==='
                    df -h
                    
                    echo '=== Memory Usage ==='
                    free -h
                    
                    echo '=== Network Connectivity ==='
                    curl -f http://localhost:8080/actuator/health || echo 'Backend health check failed'
                  "

            - name: Log Check Test
              if: ${{ github.event.inputs.test_type == 'log_check' }}
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
                    cd ${{ secrets.DEPLOY_PATH }}
                    
                    echo '=== Backend Logs (Last 50 lines) ==='
                    docker-compose logs --tail=50 backend
                    
                    echo '=== Nginx Logs (Last 20 lines) ==='
                    docker-compose logs --tail=20 nginx
                    
                    echo '=== Database Logs (Last 20 lines) ==='
                    docker-compose logs --tail=20 db
                  "
